(require 'malkav-company)
;; (require 'malkav-auto-complete)
(require 'malkav-c)
;; (require 'malkav-clang)
(require 'malkav-emacs-lisp)
;; (require 'malkav-opascal)
(require 'malkav-python)
(require 'malkav-ruby)
